import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { dm_sans } from "@/app/ui/fonts"
import Sidebar from './components/Sidebar'
import cn from 'classnames'

import '@/app/ui/global.scss'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout({
    children,
  }: {
    children: ReactNode
  }) {
    return (
      <html lang="en" className={cn(dm_sans.variable)}>
        <body>
          <main className='w-screen min-h-screen grid grid-cols-[350px_minmax(900px,_1fr)] bg-black'>
            <Sidebar/>
            <div className="pt-3 pb-3 pr-3">
              {children}
            </div>
          </main>
        </body>
      </html>
    )
  }