import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { dm_sans } from "@/app/ui/fonts"
import cn from 'classnames'

import '@/app/ui/global.scss'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout({
    children,
  }: {
    children: ReactNode
  }) {
    return (
      <html lang="en" className={cn(dm_sans.variable)}>
        <body>
          <main>
            {children}
          </main>
        </body>
      </html>
    )
  }